/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.osate.xtext.emv3.ui.AbstractEmv3UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Emv3UiModule extends AbstractEmv3UiModule {
  public Emv3UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
