/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.emv3.impl;

import org.eclipse.emf.ecore.EClass;

import org.osate.aadlv3.aadlv3.impl.PackageElementImpl;

import org.osate.xtext.emv3.emv3.Emv3Package;
import org.osate.xtext.emv3.emv3.ErrorType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Error Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ErrorTypeImpl extends PackageElementImpl implements ErrorType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ErrorTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Emv3Package.Literals.ERROR_TYPE;
  }

} //ErrorTypeImpl
