/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.validation;

import org.osate.xtext.emv3.validation.AbstractEmv3Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Emv3Validator extends AbstractEmv3Validator {
}
