/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ide;

import org.osate.xtext.emv3.ide.AbstractEmv3IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Emv3IdeModule extends AbstractEmv3IdeModule {
}
