/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.osate.xtext.emv3.Emv3RuntimeModule;
import org.osate.xtext.emv3.Emv3StandaloneSetup;
import org.osate.xtext.emv3.ide.Emv3IdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Emv3IdeSetup extends Emv3StandaloneSetup {
  @Override
  public Injector createInjector() {
    Emv3RuntimeModule _emv3RuntimeModule = new Emv3RuntimeModule();
    Emv3IdeModule _emv3IdeModule = new Emv3IdeModule();
    return Guice.createInjector(Modules2.mixin(_emv3RuntimeModule, _emv3IdeModule));
  }
}
