/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.osate.xtext.emv3.parser.antlr.internal.InternalEmv3Parser;
import org.osate.xtext.emv3.services.Emv3GrammarAccess;

public class Emv3Parser extends AbstractAntlrParser {

	@Inject
	private Emv3GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEmv3Parser createParser(XtextTokenStream stream) {
		return new InternalEmv3Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PackageEMV3";
	}

	public Emv3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Emv3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
