/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Emv3AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/osate/xtext/emv3/parser/antlr/internal/InternalEmv3.tokens");
	}
}
