/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osate.xtext.emv3.ui.internal.Emv3Activator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Emv3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Emv3Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Emv3Activator activator = Emv3Activator.getInstance();
		return activator != null ? activator.getInjector(Emv3Activator.ORG_OSATE_XTEXT_EMV3_EMV3) : null;
	}

}
