/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ui.contentassist;

import org.osate.xtext.emv3.ui.contentassist.AbstractEmv3ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Emv3ProposalProvider extends AbstractEmv3ProposalProvider {
}
