/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.osate.xtext.emv3.Emv3RuntimeModule
import org.osate.xtext.emv3.Emv3StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Emv3IdeSetup extends Emv3StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Emv3RuntimeModule, new Emv3IdeModule))
	}
	
}
