/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.emv3;

import org.eclipse.emf.common.util.EList;

import org.osate.aadlv3.aadlv3.PackageElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subclause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osate.xtext.emv3.emv3.Emv3Subclause#getEmv3statement <em>Emv3statement</em>}</li>
 * </ul>
 *
 * @see org.osate.xtext.emv3.emv3.Emv3Package#getEmv3Subclause()
 * @model
 * @generated
 */
public interface Emv3Subclause extends PackageElement
{
  /**
   * Returns the value of the '<em><b>Emv3statement</b></em>' containment reference list.
   * The list contents are of type {@link org.osate.xtext.emv3.emv3.ErrorPropagation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Emv3statement</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emv3statement</em>' containment reference list.
   * @see org.osate.xtext.emv3.emv3.Emv3Package#getEmv3Subclause_Emv3statement()
   * @model containment="true"
   * @generated
   */
  EList<ErrorPropagation> getEmv3statement();

} // Emv3Subclause
