/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.emv3;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Propagation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.osate.xtext.emv3.emv3.ErrorPropagation#getName <em>Name</em>}</li>
 *   <li>{@link org.osate.xtext.emv3.emv3.ErrorPropagation#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.osate.xtext.emv3.emv3.Emv3Package#getErrorPropagation()
 * @model
 * @generated
 */
public interface ErrorPropagation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.osate.xtext.emv3.emv3.Emv3Package#getErrorPropagation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.osate.xtext.emv3.emv3.ErrorPropagation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ErrorType)
   * @see org.osate.xtext.emv3.emv3.Emv3Package#getErrorPropagation_Type()
   * @model
   * @generated
   */
  ErrorType getType();

  /**
   * Sets the value of the '{@link org.osate.xtext.emv3.emv3.ErrorPropagation#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ErrorType value);

} // ErrorPropagation
