/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.emv3;

import org.osate.aadlv3.aadlv3.PackageElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.osate.xtext.emv3.emv3.Emv3Package#getErrorType()
 * @model
 * @generated
 */
public interface ErrorType extends PackageElement
{
} // ErrorType
