/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3;

import org.osate.xtext.emv3.Emv3StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Emv3StandaloneSetup extends Emv3StandaloneSetupGenerated {
  public static void doSetup() {
    new Emv3StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
