/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3;

import org.osate.xtext.emv3.AbstractEmv3RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Emv3RuntimeModule extends AbstractEmv3RuntimeModule {
}
