/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractEmv3Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.osate.xtext.emv3.emv3.Emv3Package.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.osate.org/aadlv3/Aadlv3"));
		return result;
	}
}
