/*
 * generated by Xtext 2.14.0
 */
package org.osate.xtext.aadlv3


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AadlV3StandaloneSetup extends AadlV3StandaloneSetupGenerated {

	def static void doSetup() {
		new AadlV3StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
