/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Emv3RuntimeModule extends AbstractEmv3RuntimeModule {
}
