<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aadlv3" nsURI="http://www.osate.org/aadlv3/Aadlv3" nsPrefix="aadlv3">
  <eClassifiers xsi:type="ecore:EClass" name="PackageDeclaration" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PackageElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPropertyAssociations"
        upperBound="-1" eType="#//PropertyAssociation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="private" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDefinition" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentCategories" upperBound="-1"
        eType="#//ComponentCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureCategories" upperBound="-1"
        eType="#//FeatureCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationTypes" upperBound="-1"
        eType="#//AssociationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertySet" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//PropertyDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inModes" upperBound="-1"
        eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" abstract="true" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//ComponentCategory"
        defaultValueLiteral="interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClassifiers" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useModes" eType="#//StateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inheritsModes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annexSubclause" upperBound="-1"
        eType="#//AnnexSubclause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRealization" abstract="true"
      eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cachedInterfaceReference"
        ordered="false" eType="#//ComponentInterface" transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifierAssignments"
        upperBound="-1" eType="#//ClassifierAssignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInterface" eSuperTypes="#//Classifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useProperties" upperBound="-1"
        eType="#//PropertySet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentImplementation" eSuperTypes="#//ComponentRealization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Subcomponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowAssignments" upperBound="-1"
        eType="#//PathSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//PathSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentConfiguration" eSuperTypes="#//ComponentRealization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ConfigurationParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//FeatureDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//FeatureCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeReference" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propagation" eType="#//DirectionalLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subcomponent" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//ComponentCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeReferences" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Subcomponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationType" eType="#//AssociationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingType" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ModelElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//ModelElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidirectional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annexSubclause" upperBound="-1"
        eType="#//AnnexSubclause"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathSequence" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ModelElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PathElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathElement" eSuperTypes="#//ModelElementReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" upperBound="-1"
        eType="#//PathElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//PathElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ModelElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifierAssignments"
        upperBound="-1" eType="#//ClassifierAssignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedClassifiers" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPropertyAssociations"
        upperBound="-1" eType="#//PropertyAssociation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Association" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annexSubclause" upperBound="-1"
        eType="#//AnnexSubclause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierAssignmentPattern" eSuperTypes="#//ClassifierAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPattern" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ModelElementReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationParameter" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationActual">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//ConfigurationParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedClassifiers" upperBound="-1"
        eType="#//TypeReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workingset" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceRoots" upperBound="-1"
        eType="#//InstanceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useProperties" upperBound="-1"
        eType="#//PropertySet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceConfiguration" eSuperTypes="#//Subcomponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyConstraint" eType="#//PropertyConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedProperty" eType="#//PropertyDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression" eType="#//MultiLiteralConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentCategory">
    <eLiterals name="interface" literal="interface"/>
    <eLiterals name="thread" value="1" literal="thread"/>
    <eLiterals name="system" value="2" literal="system"/>
    <eLiterals name="process" value="3" literal="process"/>
    <eLiterals name="processor" value="4" literal="processor"/>
    <eLiterals name="memory" value="5" literal="memory"/>
    <eLiterals name="bus" value="6" literal="bus"/>
    <eLiterals name="device" value="7" literal="device"/>
    <eLiterals name="virtualbus" value="8" literal="virtual bus"/>
    <eLiterals name="virtualprocessor" value="9" literal="virtual processor"/>
    <eLiterals name="virtualmemory" value="10" literal="virtual memory"/>
    <eLiterals name="virtualdevice" value="11" literal="virtual device"/>
    <eLiterals name="subprogram" value="11" literal="subprogram"/>
    <eLiterals name="subprogramgroup" value="12" literal="subprogram group"/>
    <eLiterals name="threadgroup" value="13" literal="thread group"/>
    <eLiterals name="data" value="14" literal="data"/>
    <eLiterals name="abstract" value="15" literal="abstract"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureCategory">
    <eLiterals name="feature" literal="feature"/>
    <eLiterals name="port" value="1" literal="port"/>
    <eLiterals name="dataaccess" value="2" literal="data access"/>
    <eLiterals name="busaccess" value="3" literal="bus access"/>
    <eLiterals name="binding" value="4" literal="binding"/>
    <eLiterals name="interface" value="5" literal="interface"/>
    <eLiterals name="virtualbusaccess" value="6" literal="virtual bus access"/>
    <eLiterals name="subprogramaccess" value="7" literal="subprogram access"/>
    <eLiterals name="subprogramgroupaccess" value="8" literal="subprogram group access"/>
    <eLiterals name="parameter" value="9" literal="parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureDirection">
    <eLiterals name="NONE" literal="none"/>
    <eLiterals name="IN" value="1" literal="in"/>
    <eLiterals name="OUT" value="2" literal="out"/>
    <eLiterals name="INOUT" value="3" literal="in out"/>
    <eLiterals name="REQUIRES" value="4" literal="requires"/>
    <eLiterals name="PROVIDES" value="5" literal="provides"/>
    <eLiterals name="REQUIRESOUT" value="6" literal="requires out"/>
    <eLiterals name="REQUIRESINOUT" value="7" literal="requires in out"/>
    <eLiterals name="REQUIRESIN" value="8" literal="requires in"/>
    <eLiterals name="PROVIDESOUT" value="9" literal="provides out"/>
    <eLiterals name="PROVIDESINOUT" value="10" literal="provides in out"/>
    <eLiterals name="PROVIDESIN" value="11" literal="provides in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssociationType">
    <eLiterals name="connection" literal="connection"/>
    <eLiterals name="binding" value="1" literal="binding"/>
    <eLiterals name="flow" value="2" literal="flow"/>
    <eLiterals name="flowsource" value="3" literal="flow source"/>
    <eLiterals name="flowsink" value="4" literal="flow sink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedType" eSuperTypes="#//PackageElement #//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDef" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitiveType" eType="#//Primitive"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Primitive">
    <eLiterals name="BOOLEAN" literal="boolean"/>
    <eLiterals name="INTEGER" value="1" literal="integer"/>
    <eLiterals name="REAL" value="2" literal="real"/>
    <eLiterals name="STRING" value="4" literal="string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compositeType" eType="#//Composite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Composite">
    <eLiterals name="LIST" literal="list"/>
    <eLiterals name="SET" value="1" literal="set"/>
    <eLiterals name="DIRECTIONAL" value="2" literal="directional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference" eSuperTypes="#//SingleLiteral #//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reverse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//NamedType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuals" upperBound="-1"
        eType="#//ConfigurationActual" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleLiteral" abstract="true" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" abstract="true" eSuperTypes="#//SingleLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//NumberLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealLiteral" eSuperTypes="#//NumberLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//SingleLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//SingleLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectionalLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//FeatureDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECollection" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LCollection" abstract="true" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListLiteral" eSuperTypes="#//LCollection"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetLiteral" eSuperTypes="#//LCollection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiLiteralConstraint" eSuperTypes="#//LCollection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiExpressionOperation" eSuperTypes="#//ECollection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//EOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LOperator">
    <eLiterals name="ANY" literal="any"/>
    <eLiterals name="ALL" value="1" literal="all"/>
    <eLiterals name="ONEOF" value="3" literal="oneof"/>
    <eLiterals name="KOFN" value="2" literal="kofn"/>
    <eLiterals name="KORMORE" value="4" literal="kormore"/>
    <eLiterals name="KORLESS" value="5" literal="korless"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EOperator">
    <eLiterals name="OR" literal="or"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ModelElementReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//PropertyDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyAssociationType"
        eType="#//PropertyAssociationType" defaultValueLiteral="FinalValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyAssociation" eType="#//PropertyAssociation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyAssociationType">
    <eLiterals name="FinalValue"/>
    <eLiterals name="VariableValue" value="1"/>
    <eLiterals name="DefaultValue" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//ModelElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionTriggerAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" ordered="false"
        upperBound="-1" eType="#//ModelElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModeAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnexSubclause" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnexLibrary" eSuperTypes="#//PackageDeclaration"/>
</ecore:EPackage>
