<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="av3instance" nsURI="http://www.osate.org/aadlv3/AV3Instance"
    nsPrefix="av3instance">
  <eClassifiers xsi:type="ecore:EClass" name="InstanceObject" abstract="true" eSuperTypes="Aadlv3.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingAssociations" ordered="false"
        upperBound="-1" eType="#//AssociationInstance" transient="true" derived="true"
        resolveProxies="false" eOpposite="#//AssociationInstance/destination"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingAssociations" ordered="false"
        upperBound="-1" eType="#//AssociationInstance" transient="true" derived="true"
        resolveProxies="false" eOpposite="#//AssociationInstance/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inStates" upperBound="-1"
        eType="#//StateInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass Aadlv3.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EEnum Aadlv3.ecore#//FeatureDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EEnum Aadlv3.ecore#//FeatureCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//FeatureInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EEnum Aadlv3.ecore#//ComponentCategory"
        defaultValueLiteral="interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ComponentInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="ecore:EClass Aadlv3.ecore#//Subcomponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//AssociationInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//FeatureInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//PathInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//BehaviorInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generators" upperBound="-1"
        eType="#//GeneratorInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateVariables" upperBound="-1"
        eType="#//StateVariableInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ConstrainedInstanceObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateTransitions" upperBound="-1"
        eType="#//StateTransitionInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateSynchronizations"
        upperBound="-1" eType="#//StateSynchronizationInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationType" eType="ecore:EEnum Aadlv3.ecore#//AssociationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="association" eType="ecore:EClass Aadlv3.ecore#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        eType="#//InstanceObject" resolveProxies="false" eOpposite="#//InstanceObject/outgoingAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" ordered="false"
        eType="#//InstanceObject" resolveProxies="false" eOpposite="#//InstanceObject/incomingAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceDelegates" upperBound="-1"
        eType="ecore:EClass Aadlv3.ecore#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationDelegates" upperBound="-1"
        eType="ecore:EClass Aadlv3.ecore#//Association"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidirectional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//InstanceObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="ecore:EClass Aadlv3.ecore#//PathSequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="ecore:EClass Aadlv3.ecore#//Behavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass Aadlv3.ecore#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ConstrainedInstanceObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EEnum Aadlv3.ecore#//BehaviorCategory"
        defaultValueLiteral="flow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generator" eType="ecore:EClass Aadlv3.ecore#//Generator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedLiterals" upperBound="-1"
        eType="#//ConstrainedInstanceObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrainedInstanceObject" eSuperTypes="#//InstanceObject Aadlv3.ecore#//Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceObject" eType="#//InstanceObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="ecore:EClass Aadlv3.ecore#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outgoing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVariableInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//StateInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateVariable" eType="ecore:EClass Aadlv3.ecore#//StateVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//StateInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateInstance" eSuperTypes="#//InstanceObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateTransitionInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateTransition" eType="ecore:EClass Aadlv3.ecore#//StateTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass Aadlv3.ecore#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//StateInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateSynchronizationInstance" eSuperTypes="#//InstanceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateSynchronization" eType="ecore:EClass Aadlv3.ecore#//StateSynchronization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass Aadlv3.ecore#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" eType="#//StateInstance"/>
  </eClassifiers>
</ecore:EPackage>
