/**
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.scoping;

import org.osate.xtext.emv3.scoping.AbstractEmv3ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Emv3ScopeProvider extends AbstractEmv3ScopeProvider {
}
