/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEmv3ScopeProvider extends DelegatingScopeProvider {
}
