/**
 * Copyright 2018 Carnegie Mellon University. All Rights Reserved.
 * 
 * NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE
 * MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO
 * WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING,
 * BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY,
 * EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON
 * UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM
 * PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 * 
 * Released under the Eclipse Public License (http://www.eclipse.org/org/documents/epl-v10.php)
 * 
 * See COPYRIGHT file for full details.
 */
package org.osate.aadlv3.aadlv3.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.osate.aadlv3.aadlv3.util.Aadlv3AdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Aadlv3ItemProviderAdapterFactory extends Aadlv3AdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Aadlv3ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PackageDeclaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PackageDeclarationItemProvider packageDeclarationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PackageDeclaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPackageDeclarationAdapter() {
		if (packageDeclarationItemProvider == null) {
			packageDeclarationItemProvider = new PackageDeclarationItemProvider(this);
		}

		return packageDeclarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PropertyDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyDefinitionItemProvider propertyDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PropertyDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyDefinitionAdapter() {
		if (propertyDefinitionItemProvider == null) {
			propertyDefinitionItemProvider = new PropertyDefinitionItemProvider(this);
		}

		return propertyDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PropertySet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertySetItemProvider propertySetItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PropertySet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertySetAdapter() {
		if (propertySetItemProvider == null) {
			propertySetItemProvider = new PropertySetItemProvider(this);
		}

		return propertySetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ComponentInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentInterfaceItemProvider componentInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ComponentInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentInterfaceAdapter() {
		if (componentInterfaceItemProvider == null) {
			componentInterfaceItemProvider = new ComponentInterfaceItemProvider(this);
		}

		return componentInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ComponentImplementation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentImplementationItemProvider componentImplementationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ComponentImplementation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentImplementationAdapter() {
		if (componentImplementationItemProvider == null) {
			componentImplementationItemProvider = new ComponentImplementationItemProvider(this);
		}

		return componentImplementationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ComponentConfiguration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentConfigurationItemProvider componentConfigurationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ComponentConfiguration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentConfigurationAdapter() {
		if (componentConfigurationItemProvider == null) {
			componentConfigurationItemProvider = new ComponentConfigurationItemProvider(this);
		}

		return componentConfigurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Feature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureItemProvider featureItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Feature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureAdapter() {
		if (featureItemProvider == null) {
			featureItemProvider = new FeatureItemProvider(this);
		}

		return featureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Subcomponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubcomponentItemProvider subcomponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Subcomponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubcomponentAdapter() {
		if (subcomponentItemProvider == null) {
			subcomponentItemProvider = new SubcomponentItemProvider(this);
		}

		return subcomponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Association} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationItemProvider associationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Association}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationAdapter() {
		if (associationItemProvider == null) {
			associationItemProvider = new AssociationItemProvider(this);
		}

		return associationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ModelElementReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelElementReferenceItemProvider modelElementReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ModelElementReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelElementReferenceAdapter() {
		if (modelElementReferenceItemProvider == null) {
			modelElementReferenceItemProvider = new ModelElementReferenceItemProvider(this);
		}

		return modelElementReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ConfigurationParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationParameterItemProvider configurationParameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ConfigurationParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurationParameterAdapter() {
		if (configurationParameterItemProvider == null) {
			configurationParameterItemProvider = new ConfigurationParameterItemProvider(this);
		}

		return configurationParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.TypeReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeReferenceItemProvider typeReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.TypeReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeReferenceAdapter() {
		if (typeReferenceItemProvider == null) {
			typeReferenceItemProvider = new TypeReferenceItemProvider(this);
		}

		return typeReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.NamedType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedTypeItemProvider namedTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.NamedType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedTypeAdapter() {
		if (namedTypeItemProvider == null) {
			namedTypeItemProvider = new NamedTypeItemProvider(this);
		}

		return namedTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ConfigurationActual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationActualItemProvider configurationActualItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ConfigurationActual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurationActualAdapter() {
		if (configurationActualItemProvider == null) {
			configurationActualItemProvider = new ConfigurationActualItemProvider(this);
		}

		return configurationActualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Workingset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkingsetItemProvider workingsetItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Workingset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkingsetAdapter() {
		if (workingsetItemProvider == null) {
			workingsetItemProvider = new WorkingsetItemProvider(this);
		}

		return workingsetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.NumberLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumberLiteralItemProvider numberLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.NumberLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumberLiteralAdapter() {
		if (numberLiteralItemProvider == null) {
			numberLiteralItemProvider = new NumberLiteralItemProvider(this);
		}

		return numberLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.IntegerLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegerLiteralItemProvider integerLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.IntegerLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegerLiteralAdapter() {
		if (integerLiteralItemProvider == null) {
			integerLiteralItemProvider = new IntegerLiteralItemProvider(this);
		}

		return integerLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.RealLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RealLiteralItemProvider realLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.RealLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRealLiteralAdapter() {
		if (realLiteralItemProvider == null) {
			realLiteralItemProvider = new RealLiteralItemProvider(this);
		}

		return realLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.StringLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StringLiteralItemProvider stringLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.StringLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStringLiteralAdapter() {
		if (stringLiteralItemProvider == null) {
			stringLiteralItemProvider = new StringLiteralItemProvider(this);
		}

		return stringLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.BooleanLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanLiteralItemProvider booleanLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.BooleanLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanLiteralAdapter() {
		if (booleanLiteralItemProvider == null) {
			booleanLiteralItemProvider = new BooleanLiteralItemProvider(this);
		}

		return booleanLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ListLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListLiteralItemProvider listLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ListLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListLiteralAdapter() {
		if (listLiteralItemProvider == null) {
			listLiteralItemProvider = new ListLiteralItemProvider(this);
		}

		return listLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.SetLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetLiteralItemProvider setLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.SetLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetLiteralAdapter() {
		if (setLiteralItemProvider == null) {
			setLiteralItemProvider = new SetLiteralItemProvider(this);
		}

		return setLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.DirectionalLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectionalLiteralItemProvider directionalLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.DirectionalLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDirectionalLiteralAdapter() {
		if (directionalLiteralItemProvider == null) {
			directionalLiteralItemProvider = new DirectionalLiteralItemProvider(this);
		}

		return directionalLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ECollection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ECollectionItemProvider eCollectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ECollection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createECollectionAdapter() {
		if (eCollectionItemProvider == null) {
			eCollectionItemProvider = new ECollectionItemProvider(this);
		}

		return eCollectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.LCollection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LCollectionItemProvider lCollectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.LCollection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLCollectionAdapter() {
		if (lCollectionItemProvider == null) {
			lCollectionItemProvider = new LCollectionItemProvider(this);
		}

		return lCollectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Literal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiteralItemProvider literalItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Literal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiteralAdapter() {
		if (literalItemProvider == null) {
			literalItemProvider = new LiteralItemProvider(this);
		}

		return literalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.SingleLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SingleLiteralItemProvider singleLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.SingleLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSingleLiteralAdapter() {
		if (singleLiteralItemProvider == null) {
			singleLiteralItemProvider = new SingleLiteralItemProvider(this);
		}

		return singleLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Expression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExpressionItemProvider expressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Expression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExpressionAdapter() {
		if (expressionItemProvider == null) {
			expressionItemProvider = new ExpressionItemProvider(this);
		}

		return expressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.MultiLiteralOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiLiteralOperationItemProvider multiLiteralOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.MultiLiteralOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiLiteralOperationAdapter() {
		if (multiLiteralOperationItemProvider == null) {
			multiLiteralOperationItemProvider = new MultiLiteralOperationItemProvider(this);
		}

		return multiLiteralOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.MultiExpressionOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiExpressionOperationItemProvider multiExpressionOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.MultiExpressionOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiExpressionOperationAdapter() {
		if (multiExpressionOperationItemProvider == null) {
			multiExpressionOperationItemProvider = new MultiExpressionOperationItemProvider(this);
		}

		return multiExpressionOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PropertyAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyAssociationItemProvider propertyAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PropertyAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAssociationAdapter() {
		if (propertyAssociationItemProvider == null) {
			propertyAssociationItemProvider = new PropertyAssociationItemProvider(this);
		}

		return propertyAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.State} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateItemProvider stateItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateAdapter() {
		if (stateItemProvider == null) {
			stateItemProvider = new StateItemProvider(this);
		}

		return stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.Transition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionItemProvider transitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.Transition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionAdapter() {
		if (transitionItemProvider == null) {
			transitionItemProvider = new TransitionItemProvider(this);
		}

		return transitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.TransitionTriggerAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionTriggerAssignmentItemProvider transitionTriggerAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.TransitionTriggerAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionTriggerAssignmentAdapter() {
		if (transitionTriggerAssignmentItemProvider == null) {
			transitionTriggerAssignmentItemProvider = new TransitionTriggerAssignmentItemProvider(this);
		}

		return transitionTriggerAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ModeAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModeAssignmentItemProvider modeAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ModeAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModeAssignmentAdapter() {
		if (modeAssignmentItemProvider == null) {
			modeAssignmentItemProvider = new ModeAssignmentItemProvider(this);
		}

		return modeAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.StateMachine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateMachineItemProvider stateMachineItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.StateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateMachineAdapter() {
		if (stateMachineItemProvider == null) {
			stateMachineItemProvider = new StateMachineItemProvider(this);
		}

		return stateMachineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.AnnexSubclause} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnexSubclauseItemProvider annexSubclauseItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.AnnexSubclause}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnexSubclauseAdapter() {
		if (annexSubclauseItemProvider == null) {
			annexSubclauseItemProvider = new AnnexSubclauseItemProvider(this);
		}

		return annexSubclauseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.AnnexLibrary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnexLibraryItemProvider annexLibraryItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.AnnexLibrary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnexLibraryAdapter() {
		if (annexLibraryItemProvider == null) {
			annexLibraryItemProvider = new AnnexLibraryItemProvider(this);
		}

		return annexLibraryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.TypeDecl} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeDeclItemProvider typeDeclItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.TypeDecl}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeDeclAdapter() {
		if (typeDeclItemProvider == null) {
			typeDeclItemProvider = new TypeDeclItemProvider(this);
		}

		return typeDeclItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PrimitiveType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveTypeItemProvider primitiveTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PrimitiveType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveTypeAdapter() {
		if (primitiveTypeItemProvider == null) {
			primitiveTypeItemProvider = new PrimitiveTypeItemProvider(this);
		}

		return primitiveTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.CompositeType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeTypeItemProvider compositeTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.CompositeType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeTypeAdapter() {
		if (compositeTypeItemProvider == null) {
			compositeTypeItemProvider = new CompositeTypeItemProvider(this);
		}

		return compositeTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PathElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PathElementItemProvider pathElementItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PathElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPathElementAdapter() {
		if (pathElementItemProvider == null) {
			pathElementItemProvider = new PathElementItemProvider(this);
		}

		return pathElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ClassifierAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassifierAssignmentItemProvider classifierAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ClassifierAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassifierAssignmentAdapter() {
		if (classifierAssignmentItemProvider == null) {
			classifierAssignmentItemProvider = new ClassifierAssignmentItemProvider(this);
		}

		return classifierAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.ClassifierAssignmentPattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassifierAssignmentPatternItemProvider classifierAssignmentPatternItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.ClassifierAssignmentPattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassifierAssignmentPatternAdapter() {
		if (classifierAssignmentPatternItemProvider == null) {
			classifierAssignmentPatternItemProvider = new ClassifierAssignmentPatternItemProvider(this);
		}

		return classifierAssignmentPatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.osate.aadlv3.aadlv3.PathSequence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PathSequenceItemProvider pathSequenceItemProvider;

	/**
	 * This creates an adapter for a {@link org.osate.aadlv3.aadlv3.PathSequence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPathSequenceAdapter() {
		if (pathSequenceItemProvider == null) {
			pathSequenceItemProvider = new PathSequenceItemProvider(this);
		}

		return pathSequenceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (packageDeclarationItemProvider != null)
			packageDeclarationItemProvider.dispose();
		if (propertyDefinitionItemProvider != null)
			propertyDefinitionItemProvider.dispose();
		if (propertySetItemProvider != null)
			propertySetItemProvider.dispose();
		if (componentInterfaceItemProvider != null)
			componentInterfaceItemProvider.dispose();
		if (componentImplementationItemProvider != null)
			componentImplementationItemProvider.dispose();
		if (componentConfigurationItemProvider != null)
			componentConfigurationItemProvider.dispose();
		if (featureItemProvider != null)
			featureItemProvider.dispose();
		if (subcomponentItemProvider != null)
			subcomponentItemProvider.dispose();
		if (importItemProvider != null)
			importItemProvider.dispose();
		if (associationItemProvider != null)
			associationItemProvider.dispose();
		if (pathSequenceItemProvider != null)
			pathSequenceItemProvider.dispose();
		if (pathElementItemProvider != null)
			pathElementItemProvider.dispose();
		if (classifierAssignmentItemProvider != null)
			classifierAssignmentItemProvider.dispose();
		if (classifierAssignmentPatternItemProvider != null)
			classifierAssignmentPatternItemProvider.dispose();
		if (modelElementReferenceItemProvider != null)
			modelElementReferenceItemProvider.dispose();
		if (configurationParameterItemProvider != null)
			configurationParameterItemProvider.dispose();
		if (configurationActualItemProvider != null)
			configurationActualItemProvider.dispose();
		if (workingsetItemProvider != null)
			workingsetItemProvider.dispose();
		if (namedTypeItemProvider != null)
			namedTypeItemProvider.dispose();
		if (typeDeclItemProvider != null)
			typeDeclItemProvider.dispose();
		if (primitiveTypeItemProvider != null)
			primitiveTypeItemProvider.dispose();
		if (compositeTypeItemProvider != null)
			compositeTypeItemProvider.dispose();
		if (typeReferenceItemProvider != null)
			typeReferenceItemProvider.dispose();
		if (literalItemProvider != null)
			literalItemProvider.dispose();
		if (singleLiteralItemProvider != null)
			singleLiteralItemProvider.dispose();
		if (numberLiteralItemProvider != null)
			numberLiteralItemProvider.dispose();
		if (integerLiteralItemProvider != null)
			integerLiteralItemProvider.dispose();
		if (realLiteralItemProvider != null)
			realLiteralItemProvider.dispose();
		if (stringLiteralItemProvider != null)
			stringLiteralItemProvider.dispose();
		if (booleanLiteralItemProvider != null)
			booleanLiteralItemProvider.dispose();
		if (directionalLiteralItemProvider != null)
			directionalLiteralItemProvider.dispose();
		if (eCollectionItemProvider != null)
			eCollectionItemProvider.dispose();
		if (lCollectionItemProvider != null)
			lCollectionItemProvider.dispose();
		if (listLiteralItemProvider != null)
			listLiteralItemProvider.dispose();
		if (setLiteralItemProvider != null)
			setLiteralItemProvider.dispose();
		if (expressionItemProvider != null)
			expressionItemProvider.dispose();
		if (multiLiteralOperationItemProvider != null)
			multiLiteralOperationItemProvider.dispose();
		if (multiExpressionOperationItemProvider != null)
			multiExpressionOperationItemProvider.dispose();
		if (propertyAssociationItemProvider != null)
			propertyAssociationItemProvider.dispose();
		if (stateItemProvider != null)
			stateItemProvider.dispose();
		if (transitionItemProvider != null)
			transitionItemProvider.dispose();
		if (transitionTriggerAssignmentItemProvider != null)
			transitionTriggerAssignmentItemProvider.dispose();
		if (modeAssignmentItemProvider != null)
			modeAssignmentItemProvider.dispose();
		if (stateMachineItemProvider != null)
			stateMachineItemProvider.dispose();
		if (annexSubclauseItemProvider != null)
			annexSubclauseItemProvider.dispose();
		if (annexLibraryItemProvider != null)
			annexLibraryItemProvider.dispose();
	}

}
