/*
 * generated by Xtext 2.14.0
 */
package org.osate.xtext.aadlv3.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.osate.aadlv3.aadlv3.PackageDeclaration

@ExtendWith(InjectionExtension)
@InjectWith(AadlV3InjectorProvider)
class AadlV3ParsingTest {
	@Inject
	ParseHelper<PackageDeclaration> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
package Basic 
// example with nested packages, duplicate feature name in original and extension,
// property associated with model element and as contained property in classifier
	type date ;
	type person ;
	type int;
	
end ;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		val con = result.eResource.contents.get(0)
		System.out.println("Name "+(con as PackageDeclaration).name)
	}
}
