/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.osate.aadlv3.aadlv3.PackageDeclaration

@ExtendWith(InjectionExtension)
@InjectWith(Emv3InjectorProvider)
class Emv3ParsingTest {
	@Inject
	ParseHelper<PackageDeclaration> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
