/*
 * generated by Xtext 2.16.0
 */
package org.osate.xtext.emv3.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.osate.xtext.emv3.ui.internal.Emv3Activator;

public class Emv3UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Emv3Activator.getInstance().getInjector("org.osate.xtext.emv3.Emv3");
	}

}
